name: Bump version
on:
 push:
   branches:
     [master, dev, feature, release]
jobs:
 build:
   runs-on: ubuntu-latest
   env: 
     REVISION: '-SNAPSHOT'
   steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Set up JDK 1.11
       uses: actions/setup-java@v1
       with:
         java-version: 1.11
   
     - name: Master branch
       if: github.ref == 'refs/heads/master'
       env:
         REVISION: '-${{github.run_number}}'
       run: mvn clean install -Drevision=$REVISION -Dbuild_number

     - name: Release branch
       if: github.ref == 'refs/heads/release'
       env:
         REVISION: '-rc-${{github.run_number}}'
       run: mvn clean install -Drevision=$REVISION -Dbuild_number

     - name: Develop branch
       if: github.ref == 'refs/heads/dev'
       run: $REVISION = '-0-SNAPSHOT' echo "!!!" $REVISION

     - name: Feature branch
       if: github.ref == 'refs/heads/feature'
       env:
         REVISION: '-${{github.ref}}_0-SNAPSHOT'
       run: echo "!!!" $REVISION
         
     - name: Maven
       env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         API_TESTS_VERBOSE_LOGGING: false
       run: mvn -V -e -B -ntp
          clean install
          -Papi-tests-infrastructure
          -Papi-tests
          -Pjacoco -Dsonar.coverage.jacoco.xmlReportPaths=${{ github.workspace }}/home-api-tests/target/site/jacoco-aggregate/jacoco.xml
          -Dpostgres.user=${{secrets.POSTGRES_USER}}
          -Dpostgres.password=${{secrets.POSTGRES_PASSWORD}}
          -Dapi.tests.verbose.logging=${{env.API_TESTS_VERBOSE_LOGGING}}
          -Dgithub.packages.read.username=${{secrets.PACKAGES_READ_USERNAME}}
          -Dgithub.packages.read.token=${{secrets.PACKAGES_READ_TOKEN}}
          -Drev=$REVISION


# name: Semantic Version

# on:
#   push:
#     tags:
#       - '*'

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Process version of the tag
#         id: version
#         uses: ncipollo/semantic-version-action@v1
#       - name: Dump steps context
#         env:
#           STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
#         run: echo "$STEPS_CONTEXT"
#       - name: Dump previous tag
#         env:
#           PREVIOUS_TAG: ${{ steps.version.outputs.previous_tag }}
#         run: echo "$PREVIOUS_TAG"
